"""Brain — model-agnostic LLM provider abstraction (stdlib only)."""

from __future__ import annotations

from robots.brain.capabilities import (
    HANDSHAKE_PROMPT,
    HANDSHAKE_TTL_SECONDS,
    TIER_1_LOCAL,
    TIER_2_MID,
    TIER_3_FLAGSHIP,
    CapabilityProfile,
    adaptive_params,
    apply_live_facts,
    classify_model,
    handshake_cache_path,
    load_cached_handshake,
    parse_model_facts,
    parse_param_count,
    probe_capabilities,
    resolve_brain_config,
    resolve_runtime,
    save_cached_handshake,
    step_down_tier,
    tier_for_params,
    validate_handshake_text,
    verify_generation,
)
from robots.brain.prompt import build_prompt, repair_plan
from robots.brain.provider import (
    BrainError,
    MockProvider,
    ModelOptions,
    ModelResponse,
    OllamaProvider,
    OpenAICompatibleProvider,
    ProbeInfo,
    provider_from_config,
)
from robots.brain.redact import is_secret_path, redact_text, secret_marker
from robots.brain.resources import HostSnapshot, ThrottleDecision, check, snapshot

__all__ = [
    "HANDSHAKE_PROMPT",
    "HANDSHAKE_TTL_SECONDS",
    "TIER_1_LOCAL",
    "TIER_2_MID",
    "TIER_3_FLAGSHIP",
    "BrainError",
    "CapabilityProfile",
    "HostSnapshot",
    "MockProvider",
    "ModelOptions",
    "ModelResponse",
    "OllamaProvider",
    "OpenAICompatibleProvider",
    "ProbeInfo",
    "ThrottleDecision",
    "adaptive_params",
    "apply_live_facts",
    "build_prompt",
    "check",
    "classify_model",
    "handshake_cache_path",
    "is_secret_path",
    "load_cached_handshake",
    "parse_model_facts",
    "parse_param_count",
    "probe_capabilities",
    "provider_from_config",
    "redact_text",
    "repair_plan",
    "resolve_brain_config",
    "resolve_runtime",
    "save_cached_handshake",
    "secret_marker",
    "snapshot",
    "step_down_tier",
    "tier_for_params",
    "validate_handshake_text",
    "verify_generation",
]
